### ISSUE TITLE
Website still refers to Eclipe Public License 1.0

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr.website#15]
At the bottom of "About OMR" page:

Licenses: All Eclipse OMR project materials are made available under the Eclipse Public License V1.0 and the Apache 2.0 license. You can choose which license you wish to follow. Please see our LICENSE file for more details.

This should be updated to reflect the project's new license:

Licenses: All Eclipse OMR project materials are made available under the Eclipse Public License V2.0 and the Apache 2.0 license. This Source Code may also be made available under the following
Secondary Licenses when the conditions for such availability set forth in the Eclipse Public License, v. 2.0 are satisfied: GNU General Public License, version 2 with the GNU Classpath Exception [1] and GNU General Public License, version 2 with the OpenJDK Assembly Exception [2].

[1] https://www.gnu.org/software/classpath/license.html
[2] http://openjdk.java.net/legal/assembly-exception.html

You can choose which license you wish to follow. Please see our LICENSE file for more details.

**Comment by ezephir** [comment]
While I was looking around, I noticed that all of the license headers in this repository still refer to the EPL 1.0. Is this repository going to move to EPL v2?

**Comment by 0xdaryl** [comment]
You are absolutely correct.  Thanks for pointing that out.  #18 created.
