### ISSUE TITLE
Improve the appeal: What is OMR / why do I want it?

### ISSUE THREAD

**Issue by SueChaplain** [eclipse/omr.website#6]
Following comments on putting out a clearer message about what OMR is and why you'd use it, I've expanded the opening, based on content from recent presentations and articles. I have also removed the precise list of components in this topic, because they are listed elsewhere. I also think this topic could do with a diagram, which could be based on content from Mark's slides. (An application execution environment with boxes denoting components, and the extent to which those components can be replaced by OMR)

**Comment by mstoodle** [comment]
I believe this one has been addressed, at least in the context for which it was opened.
